# Generated by Django 6.0 on 2026-01-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_remove_educacion_fecha_fin_educacion_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='subtitulo',
            field=models.CharField(blank=True, help_text='Ej: Proyecto Freelance o Académico', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='tecnologias',
            field=models.CharField(blank=True, help_text='Separa las tecnologías con comas', max_length=200, null=True),
        ),
    ]
