# Generated by Django 6.0 on 2026-01-29 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_proyecto_subtitulo_proyecto_tecnologias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='tecnologias',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
