# Generated by Django 6.0 on 2026-01-31 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0006_alter_proyecto_subtitulo_alter_proyecto_tecnologias'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reconocimiento',
        ),
        migrations.DeleteModel(
            name='Referencia',
        ),
        migrations.AlterModelOptions(
            name='certificado',
            options={'verbose_name': 'Certificado', 'verbose_name_plural': 'Certificados'},
        ),
        migrations.AlterModelOptions(
            name='educacion',
            options={'verbose_name': 'Producto Académico', 'verbose_name_plural': 'Productos Académicos'},
        ),
        migrations.AlterModelOptions(
            name='experiencia',
            options={'verbose_name': 'Experiencia', 'verbose_name_plural': 'Experiencia Laboral'},
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfil (Información Personal)'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'Producto de Venta', 'verbose_name_plural': 'Garage (Ventas)'},
        ),
        migrations.AlterModelOptions(
            name='proyecto',
            options={'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos (Portafolio)'},
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Realización'),
        ),
    ]
