# Generated by Django 6.0 on 2026-02-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0007_delete_reconocimiento_delete_referencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción detallada'),
        ),
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('Nuevo', 'Nuevo / Sellado'), ('Como Nuevo', 'Como Nuevo (10/10)'), ('Buen Estado', 'Usado - Buen Estado'), ('Detalles', 'Usado - Con detalles estéticos'), ('Reparar', 'Para piezas / A reparar')], default='Buen Estado', max_length=50, verbose_name='Condición'),
        ),
    ]
