# Generated by Django 6.0 on 2026-02-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0008_producto_descripcion_producto_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='educacion',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Finalización'),
        ),
    ]
